delete http://localhost:3001/api/blogs/66d08d2311afbc354f078e78
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtydXNobmEiLCJpZCI6IjY2ZDQzNTczODRhNTlmODhjNzI1ZTFmNyIsImlhdCI6MTcyNTE4Njk3Nn0.3zNctqnON0-L7bB5msU6sMzSqZ9anceULNPDVESKJTY